In [1]:
import pandas as pd
import numpy as np

In [2]:
#Load data :

In [3]:
df = pd.read_csv("../data/cardekho.csv")

In [ ]:
#statistic description of data:

In [4]:
print(df.head())
print(df.info())
print(df.describe())
print("Missing values per column:\n", df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

                           name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol

  seller_type transmission         owner  mileage(km/ltr/kg)  engine  \
0  Individual       Manual   First Owner               23.40  1248.0
1  Individual       Manual  Second Owner               21.14  1498.0
2  Individual       Manual   Third Owner               17.70  1497.0
3  Individual       Manual   First Owner               23.00  1396.0
4  Individual       Manual   First Owner               16.10  1298.0

  max_power  seats
0        74    5.0
1    103.52    5.0
2        78    5.0
3        90    5.0
4      88.2    5.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                8128 non-null   object
 1   year                8128 non-null   int64
 2   selling_price       8128 non-null   int64
 3   km_driven           8128 non-null   int64
 4   fuel                8128 non-null   object
 5   seller_type         8128 non-null   object
 6   transmission        8128 non-null   object
 7   owner               8128 non-null   object
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB
None
              year  selling_price     km_driven  mileage(km/ltr/kg)  \
count  8128.000000   8.128000e+03  8.128000e+03         7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04           19.418783
std       4.044249   8.062534e+05  5.655055e+04            4.037145
min    1983.000000   2.999900e+04  1.000000e+00            0.000000
25%    2011.000000   2.549990e+05  3.500000e+04           16.780000
50%    2015.000000   4.500000e+05  6.000000e+04           19.300000
75%    2017.000000   6.750000e+05  9.800000e+04           22.320000
max    2020.000000   1.000000e+07  2.360457e+06           42.000000

            engine        seats
count  7907.000000  7907.000000
mean   1458.625016     5.416719
std     503.916303     0.959588
min     624.000000     2.000000
25%    1197.000000     5.000000
50%    1248.000000     5.000000
75%    1582.000000     5.000000
max    3604.000000    14.000000
Missing values per column:
 name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             215
seats                 221
dtype: int64
Duplicate rows: 1202

In [6]:
duplicate_percentage = df.duplicated().mean() * 100
print(f"Duplicate percentage: {duplicate_percentage:.2f}%")

Duplicate percentage: 14.79%

In [ ]:
#convert column max_power type object to type float

In [7]:
df['max_power'].unique()[:30]

array(['74', '103.52', '78', '90', '88.2', '81.86', '57.5', '37', '67.1',
       '68.1', '108.45', '60', '73.9', nan, '67', '82', '88.5', '46.3',
       '88.73', '64.1', '98.6', '88.8', '83.81', '83.1', '47.3', '73.8',
       '34.2', '35', '81.83', '40.3'], dtype=object)

In [8]:
df['max_power'].nunique()

320

In [9]:
df['max_power'] = (
    df['max_power']
    .str.replace('bhp', '', regex=False)
    .str.strip()
)

df['max_power'] = pd.to_numeric(df['max_power'], errors='coerce')

In [ ]:
#check if it's work:

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                8128 non-null   object
 1   year                8128 non-null   int64
 2   selling_price       8128 non-null   int64
 3   km_driven           8128 non-null   int64
 4   fuel                8128 non-null   object
 5   seller_type         8128 non-null   object
 6   transmission        8128 non-null   object
 7   owner               8128 non-null   object
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7912 non-null   float64
 11  seats               7907 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 762.1+ KB
None

In [11]:
print(df.isnull().sum())

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             216
seats                 221
dtype: int64

In [12]:
duplicates = df[df.duplicated(keep=False)]

print("Number of duplicate rows:", len(duplicates))
duplicates

Number of duplicate rows: 1827

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
31,Fiat Palio 1.2 ELX,2003,70000,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN
32,Maruti Omni 8 Seater BSIV,2012,150000,35000,Petrol,Individual,Manual,Second Owner,14.00,796.0,35.00,5.0
33,Hyundai i20 1.2 Asta Dual Tone,2018,730000,2388,Petrol,Individual,Manual,First Owner,18.60,1197.0,81.83,5.0
34,Maruti Vitara Brezza LDi,2017,650000,16200,Diesel,Individual,Manual,First Owner,24.30,1248.0,88.50,5.0
35,Maruti Alto 800 CNG LXI Optional,2019,330000,10000,CNG,Individual,Manual,Second Owner,33.44,796.0,40.30,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7987,Renault Captur 1.5 Diesel RXT,2018,1265000,12000,Diesel,Individual,Manual,First Owner,20.37,1461.0,108.45,5.0
7988,Maruti Ciaz Alpha Diesel,2019,1025000,32000,Diesel,Individual,Manual,First Owner,28.09,1248.0,88.50,5.0
8117,Maruti Swift Dzire VDI,2015,625000,50000,Diesel,Individual,Manual,First Owner,26.59,1248.0,74.00,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70.00,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70.00,5.0

In [ ]:
#handling duplicates:

In [13]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (8128, 12)
After: (6926, 12)

In [ ]:
#handling missing value:

In [14]:
print(df.isnull().sum())

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    208
engine                208
max_power             206
seats                 208
dtype: int64

In [15]:
numeric_cols = [
    'mileage(km/ltr/kg)',
    'engine',
    'max_power',
    'seats'
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [16]:
print(df.isnull().sum())

name                  0
year                  0
selling_price         0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
mileage(km/ltr/kg)    0
engine                0
max_power             0
seats                 0
dtype: int64

In [17]:
categorical_cols = [
    'fuel',
    'seller_type',
    'transmission',
    'owner'
]

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts())

fuel:
fuel
Diesel    3755
Petrol    3077
CNG         56
LPG         38
Name: count, dtype: int64

seller_type:
seller_type
Individual          6218
Dealer               681
Trustmark Dealer      27
Name: count, dtype: int64

transmission:
transmission
Manual       6342
Automatic     584
Name: count, dtype: int64

owner:
owner
First Owner             4242
Second Owner            1974
Third Owner              536
Fourth & Above Owner     169
Test Drive Car             5
Name: count, dtype: int64

In [18]:
print("Mileage = 0:", (df['mileage(km/ltr/kg)'] == 0).sum())

print("Engine = 0:", (df['engine'] == 0).sum())

print("Max power = 0:", (df['max_power'] == 0).sum())

print("Seats <= 0:", (df['seats'] <= 0).sum())

print("Seats > 10:", (df['seats'] > 10).sum())

print("KM driven > 1,000,000:",
      (df['km_driven'] > 1_000_000).sum())

Mileage = 0: 15
Engine = 0: 0
Max power = 0: 3
Seats <= 0: 0
Seats > 10: 1
KM driven > 1,000,000: 2

In [19]:
df[df['mileage(km/ltr/kg)'] == 0]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
644,Tata Indica Vista Aura Safire Anniversary Edition,2009,135000,28900,Petrol,Individual,Manual,Second Owner,0.0,1172.0,65.00,5.0
785,Hyundai Santro Xing GL,2009,120000,90000,Petrol,Individual,Manual,Second Owner,0.0,1086.0,62.00,5.0
1649,Hyundai Santro Xing GL,2008,105000,128000,Petrol,Individual,Manual,First Owner,0.0,1086.0,62.00,5.0
1676,Mercedes-Benz M-Class ML 350 4Matic,2011,1700000,110000,Diesel,Individual,Automatic,Third Owner,0.0,2987.0,165.00,5.0
2137,Land Rover Freelander 2 TD4 HSE,2013,1650000,64788,Diesel,Dealer,Automatic,First Owner,0.0,2179.0,115.00,5.0
2366,Hyundai Santro Xing (Non-AC),2010,110000,80000,Petrol,Individual,Manual,Second Owner,0.0,1086.0,62.10,5.0
2725,Hyundai Santro Xing (Non-AC),2013,184000,15000,Petrol,Individual,Manual,First Owner,0.0,1086.0,62.10,5.0
5276,Hyundai Santro Xing GL,2008,175000,40000,Petrol,Individual,Manual,First Owner,0.0,1086.0,62.00,5.0
5843,Volkswagen Polo GT TSI BSIV,2014,574000,28080,Petrol,Dealer,Automatic,First Owner,0.0,1197.0,103.25,5.0
5846,Volkswagen Polo GT TSI BSIV,2014,575000,28100,Petrol,Dealer,Automatic,First Owner,0.0,1197.0,103.25,5.0
5900,Mahindra Bolero Pik-Up FB 1.7T,2020,679000,5000,Diesel,Individual,Manual,First Owner,0.0,2523.0,70.00,2.0
6534,Hyundai Santro Xing GL,2010,150000,110000,Petrol,Individual,Manual,First Owner,0.0,1086.0,62.00,5.0
6629,Mahindra Bolero Pik-Up CBC 1.7T,2019,722000,80000,Diesel,Individual,Manual,First Owner,0.0,2523.0,70.00,2.0
6824,Hyundai Santro Xing GL,2011,150000,40000,Petrol,Individual,Manual,Fourth & Above Owner,0.0,1086.0,62.00,5.0
7337,Mercedes-Benz GLC 220d 4MATIC,2017,3300000,60000,Diesel,Dealer,Automatic,First Owner,0.0,1950.0,194.00,5.0

In [20]:
df.loc[df['mileage(km/ltr/kg)'] == 0, 'mileage(km/ltr/kg)'] = np.nan

df['mileage(km/ltr/kg)'] = df['mileage(km/ltr/kg)'].fillna(
    df['mileage(km/ltr/kg)'].median()
)

In [21]:
df[df['mileage(km/ltr/kg)'] == 0]

Empty DataFrame
Columns: [name, year, selling_price, km_driven, fuel, seller_type, transmission, owner, mileage(km/ltr/kg), engine, max_power, seats]
Index: []

In [23]:
print("Max power = 0")
display(df[df['max_power'] == 0])

Max power = 0

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
575,Maruti Alto K10 LXI,2011,204999,97500,Petrol,Individual,Manual,First Owner,19.44,1248.0,0.0,5.0
1442,Maruti Swift Dzire VDI Optional,2017,589000,41232,Diesel,Dealer,Manual,First Owner,19.44,1248.0,0.0,5.0
2549,Tata Indica Vista Quadrajet LS,2012,240000,70000,Diesel,Individual,Manual,First Owner,19.44,1248.0,0.0,5.0

In [31]:
df.loc[df['max_power'] == 0, 'max_power'] = np.nan

df['max_power'] = df['max_power'].fillna(
    df['max_power'].median()
)

In [24]:
print("Seats > 10")
display(df[df['seats'] > 10])

Seats > 10

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
4575,Tata Winger Deluxe - Flat Roof (Non-AC),2010,235000,50000,Diesel,Individual,Manual,First Owner,10.71,1948.0,90.0,14.0

In [25]:
print("KM driven > 1,000,000")
display(df[df['km_driven'] > 1_000_000])

KM driven > 1,000,000

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
1810,Mahindra XUV500 W6 2WD,2012,500000,1500000,Diesel,Individual,Manual,First Owner,15.1,2179.0,140.00,7.0
3486,Hyundai i20 Asta 1.2,2007,550000,2360457,Petrol,Individual,Manual,Second Owner,18.6,1197.0,81.83,5.0

In [32]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nMax power = 0:",
      (df['max_power'] == 0).sum())

print("Mileage = 0:",
      (df['mileage(km/ltr/kg)'] == 0).sum())

print("Seats <= 0:",
      (df['seats'] <= 0).sum())

Missing values:
name                  0
year                  0
selling_price         0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
mileage(km/ltr/kg)    0
engine                0
max_power             0
seats                 0
dtype: int64

Duplicate rows:
0

Max power = 0: 0
Mileage = 0: 0
Seats <= 0: 0

In [33]:
#feature engineering:

In [34]:
#add column car_age based on the version of dataset 2020:
df['car_age'] = 2020 - df['year']

In [36]:
df[['year', 'car_age']].head()

   year  car_age
0  2014        6
1  2014        6
2  2006       14
3  2010       10
4  2007       13

In [37]:
print(df['car_age'].describe())

count    6926.000000
mean        6.579700
std         4.078286
min         0.000000
25%         3.000000
50%         6.000000
75%         9.000000
max        37.000000
Name: car_age, dtype: float64

In [38]:
#add column brand extracted from name of car :
df['brand'] = df['name'].str.split().str[0]

In [39]:
df[['name', 'brand']].head(10)

                                   name    brand
0                Maruti Swift Dzire VDI   Maruti
1          Skoda Rapid 1.5 TDI Ambition    Skoda
2              Honda City 2017-2020 EXi    Honda
3             Hyundai i20 Sportz Diesel  Hyundai
4                Maruti Swift VXI BSIII   Maruti
5         Hyundai Xcent 1.2 VTVT E Plus  Hyundai
6          Maruti Wagon R LXI DUO BSIII   Maruti
7                    Maruti 800 DX BSII   Maruti
8                      Toyota Etios VXD   Toyota
9  Ford Figo Diesel Celebration Edition     Ford

In [40]:
print("Number of brands:", df['brand'].nunique())

Number of brands: 32

In [41]:
print(df['brand'].value_counts())

brand
Maruti           2165
Hyundai          1267
Mahindra          723
Tata              647
Honda             362
Ford              361
Toyota            357
Chevrolet         216
Renault           206
Volkswagen        174
Nissan             73
Skoda              70
Datsun             57
BMW                47
Mercedes-Benz      46
Fiat               44
Audi               33
Jeep               22
Mitsubishi         11
Volvo               9
Jaguar              8
Isuzu               4
Force               4
Ambassador          4
Daewoo              3
MG                  3
Land                3
Kia                 3
Lexus               1
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [42]:
df[df['brand'] == 'Land'][['name', 'brand']]

                                         name brand
135         Land Rover Discovery Sport TD4 SE  Land
2137          Land Rover Freelander 2 TD4 HSE  Land
6724  Land Rover Range Rover Evoque 2.2L Pure  Land

In [45]:
df.loc[df['brand'] == 'Land', 'brand'] = 'Land Rover'

In [43]:
df[df['brand'] == 'Ashok'][['name', 'brand']]

                        name  brand
4011  Ashok Leyland Stile LE  Ashok

In [44]:
df.loc[df['brand'] == 'Ashok', 'brand'] = 'Ashok Leyland'

In [46]:
print(df['brand'].value_counts())

brand
Maruti           2165
Hyundai          1267
Mahindra          723
Tata              647
Honda             362
Ford              361
Toyota            357
Chevrolet         216
Renault           206
Volkswagen        174
Nissan             73
Skoda              70
Datsun             57
BMW                47
Mercedes-Benz      46
Fiat               44
Audi               33
Jeep               22
Mitsubishi         11
Volvo               9
Jaguar              8
Isuzu               4
Force               4
Ambassador          4
Daewoo              3
MG                  3
Land Rover          3
Kia                 3
Lexus               1
Ashok Leyland       1
Opel                1
Peugeot             1
Name: count, dtype: int64